index:
  path: /
  controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\DefaultController::register

checkout:
  path: /checkout
  controller: App\Controller\DefaultController::checkout